ci/cd:
- any:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

app:
- any:
  - changed-files:
    - any-glob-to-any-file: 'src/**'

tests:
- any:
  - changed-files:
    - any-glob-to-any-file: 'test?/**/*'  

tools:
- any:
  - changed-files:
    - any-glob-to-any-file: '.config/**'  

documentation:
- any:
  - changed-files:
    - any-glob-to-any-file: ['*.md*', '**/*.md*']

feature:
- head-branch: ['^feature', 'feature']

chore:
- head-branch: ['^chore', 'chore']

bugfix:
- head-branch: ['^bugfix', 'bugfix']

experiment:
- head-branch: ['^experiment', 'experiment']

dependabot:
- head-branch: ['^dependabot', 'dependabot']